global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.
  evaluation_interval: 15s # By default, scrape targets every 15 seconds.

rule_files:
  - 'alert.rules'

alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets:
      - "alertmanager:9093"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
    - targets: ['localhost:9090']

  - job_name: 'node-exporter'
    static_configs:
    - targets: ['node-exporter:9100']

  - job_name: 'kafka'
    static_configs:
    - targets:
      - 'kafka-1:1234'
      - 'kafka-2:1234'
      - 'kafka-3:1234'
      labels:
        env: 'dev'

  - job_name: 'zookeeper'
    static_configs:
    - targets:
      - 'zookeeper-1:1234'
      - 'zookeeper-2:1234'
      - 'zookeeper-3:1234'
      labels:
        env: 'dev'

  - job_name: 'producer'
    static_configs:
      - targets:
          - 'producer:1234'
        labels:
          env: 'dev'

  - job_name: 'consumer'
    static_configs:
      - targets:
          - "consumer:1234"
          - "consumer-1:1234"
          - "consumer-2:1234"
          - "consumer-3:1234"
        labels:
          env: 'dev'

  - job_name: 'streams'
    static_configs:
      - targets:
          - 'streams:1234'
        labels:
          env: 'dev'

  - job_name: 'ksql'
    static_configs:
      - targets:
          - 'ksqldb:1234'
        labels:
          env: 'dev'

  - job_name: 'connect'
    static_configs:
      - targets:
          - 'connect:1234'
        labels:
          env: 'dev'
          cluster: 'cluster1'

  - job_name: 'kafka-lag-exporter'
    static_configs:
      - targets:
        - 'kafka-lag-exporter:9999'
        labels:
           env: 'dev'

