{
 "title": "Kafka Connect",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "Release",
    "label": "Release",
    "query": "label_values(cp_zookeeper_initlimit, release)"
   }
  ]
 },
 "panels": [
  { "title": "Worker metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Number of Connectors",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "kafka_connect_connect_worker_metrics_connector_count"
    }
   ]
  },
  {
   "title": "Connector Startup Success Total",
   "type": "singlestat",
   "description": "The total number of connector starts that succeeded.",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "kafka_connect_connect_worker_metrics_connector_startup_success_total"
    }
   ]
  },
  {
   "title": "Connector Startup Failure Total",
   "type": "singlestat",
   "description": "The total number of connector starts that failed.",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "kafka_connect_connect_worker_metrics_connector_startup_failure_total"
    }
   ]
  },
  {
   "title": "Number of Rebalances",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "kafka_connect_connect_worker_rebalance_metrics_completed_rebalances_total"
    }
   ]
  },
  {
   "title": "Average time of Rebalances",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 1 },
   "format": "ms",
   "valueName": "avg",
   "targets": [
    {
     "expr": "kafka_connect_connect_worker_rebalance_metrics_rebalance_avg_time_ms"
    }
   ]
  },
  {
   "title": "Time since last rebalance",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 1 },
   "format": "ms",
   "valueName": "avg",
   "targets": [
    {
     "expr": "kafka_connect_connect_worker_rebalance_metrics_time_since_last_rebalance_ms"
    }
   ]
  },
  {
   "title": "Connect Metrics: IO Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_connect_connect_metrics_io_ratio",
     "legendFormat": "{{client-id}}"
    }
   ]
  },
  {
   "title": "Connect Metrics: Incoming Byte Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_connect_connect_metrics_incoming_byte_rate",
     "legendFormat": "{{client-id}}"
    }
   ]
  },
  {
   "title": "Connect Metrics: Network IO Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_connect_connect_metrics_network_io_rate",
     "legendFormat": "{{client-id}}"
    }
   ]
  },
  { "title": "Task metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "Number of Tasks",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 13 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "kafka_connect_connect_worker_metrics_task_count"
    }
   ]
  },
  {
   "title": "Task Startup Success Total",
   "type": "singlestat",
   "description": "The total number of task starts that succeeded.",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 13 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "kafka_connect_connect_worker_metrics_task_startup_success_total"
    }
   ]
  },
  {
   "title": "Task Startup Failure Total",
   "type": "singlestat",
   "description": "The total number of task starts that failed.",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 13 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "kafka_connect_connect_worker_metrics_task_startup_failure_total"
    }
   ]
  },
  {
   "title": "Batch Size Average",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_connect_connector_task_metrics_batch_size_avg",
     "legendFormat": "{{connector}}-{{task}}"
    }
   ]
  },
  {
   "title": "Batch Size Max",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_connect_connector_task_metrics_batch_size_max",
     "legendFormat": "{{connector}}-{{task}}"
    }
   ]
  },
  {
   "title": "Offset commit success percentage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "kafka_connect_connector_task_metrics_offset_commit_success_percentage",
     "legendFormat": "{{connector}}-{{task}}"
    }
   ]
  },
  {
   "title": "Offset commit Average Time",
   "type": "graph",
   "description": "The average time in milliseconds taken by this task to commit offsets",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 24 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "kafka_connect_connector_task_metrics_offset_commit_avg_time_ms",
     "legendFormat": "{{connector}}-{{task}}"
    }
   ]
  },
  {
   "title": "Partition Count",
   "type": "graph",
   "description": "The number of topic partitions assigned to this task belonging to the named sink connector in this worker.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_connect_sink_task_metrics_partition_count",
     "legendFormat": "{{connector}}-{{task}}"
    }
   ]
  },
  {
   "title": "Running ratio",
   "type": "graph",
   "description": "The fraction of time this task has spent in the running state.",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 31 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "kafka_connect_connector_task_metrics_running_ratio",
     "legendFormat": "{{connector}}-{{task}}"
    }
   ]
  }
 ]
}