{
 "title": "Kafka Streams (alternative)",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Process Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_streams_stream_metrics_process_rate"
    }
   ]
  },
  {
   "title": "Latency Avg",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_streams_stream_metrics_process_latency_avg"
    }
   ]
  },
  { "title": "Application details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Task Commit Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_streams_stream_task_metrics_commit_rate"
    }
   ]
  },
  {
   "title": "Task Commit Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_streams_stream_task_metrics_commit_latency_avg"
    }
   ]
  },
  {
   "title": "Processor Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_streams_stream_processor_node_metrics_process_rate"
    }
   ]
  },
  {
   "title": "Processors Latency Avg",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_streams_stream_processor_node_metrics_process_latency_avg"
    }
   ]
  },
  {
   "title": "Record Lateness",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_streams_stream_task_metrics_record_lateness_avg"
    }
   ]
  },
  {
   "title": "RocksDB",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 },
   "collapsed": true
  },
  {
   "title": "Latency Avg",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_streams_stream_rocksdb_state_metrics_all_latency_avg"
    }
   ]
  }
 ]
}