{
 "title": "ksqlDB",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Persistent Queries",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "_confluent_ksql_default_num_persistent_queries"
    }
   ]
  },
  {
   "title": "Active Queries",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "_confluent_ksql_default_num_active_queries  "
    }
   ]
  },
  {
   "title": "Error Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "_confluent_ksql_default_error_rate"
    }
   ]
  },
  {
   "title": "Error Queries",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "_confluent_ksql_default_ksql_engine_query_stats_error_queries  "
    }
   ]
  }
 ]
}