{
 "title": "Producers",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Outgoing byte rate",
   "type": "graph",
   "description": "The average number of bytes sent per second to the broker.\n",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(kafka_producer_producer_metrics_outgoing_byte_total{job=\"producer\"}[1m])",
     "legendFormat": "{{client_id}} - {{instance}}"
    }
   ]
  },
  {
   "title": "Outgoing byte rate per topic",
   "type": "graph",
   "description": "The average number of bytes sent per second to the broker per topic.\n",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(kafka_producer_producer_topic_metrics_byte_total{job=\"producer\"}[1m])) by (topic)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Outgoing messages per second",
   "type": "graph",
   "description": "The average number of messages sent per second to the broker.\n",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(kafka_producer_producer_metrics_record_send_total{job=\"producer\"}[1m])",
     "legendFormat": "{{client_id}} - {{instance}}"
    }
   ]
  },
  {
   "title": "Outgoing messages per second per topic",
   "type": "graph",
   "description": "The average number of messages sent per second to the broker per topic.\n",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(kafka_producer_producer_topic_metrics_record_send_total{job=\"producer\"}[1m])) by (topic)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Compression rate",
   "type": "graph",
   "description": "The average compression rate of record batches for a topic.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_producer_producer_metrics_compression_rate_avg{job=\"producer\"}",
     "legendFormat": "{{client_id}} - {{instance}}"
    }
   ]
  },
  {
   "title": "Batch size average",
   "type": "graph",
   "description": "The average number of bytes sent per partition per-request.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_producer_producer_metrics_batch_size_avg",
     "legendFormat": "{{client_id}} - {{instance}}"
    }
   ]
  },
  {
   "title": "Error rate",
   "type": "graph",
   "description": "The average per-second number of record sends that resulted in errors.\n",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(kafka_producer_producer_metrics_record_error_total{job=\"producer\"}[1m])",
     "legendFormat": "{{client_id}} - {{instance}}"
    }
   ]
  },
  {
   "title": "Retry rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_producer_producer_metrics_record_retry_rate",
     "legendFormat": "{{client_id}} - {{instance}}"
    }
   ]
  },
  {
   "title": "Produce request latency",
   "type": "graph",
   "description": "The average request latency in ms",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_producer_producer_metrics_request_latency_avg",
     "legendFormat": "{{client_id}} - {{instance}}"
    }
   ]
  },
  {
   "title": "Produce request size average",
   "type": "graph",
   "description": "The average number of records per request.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_consumer_consumer_metrics_request_size_avg",
     "legendFormat": "{{client_id}} - {{instance}}"
    }
   ]
  },
  {
   "title": "Produce request rate",
   "type": "graph",
   "description": "The average number of requests sent per second to the broker.\n",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(kafka_producer_producer_metrics_request_total{job=\"producer\"}[1m])",
     "legendFormat": "{{client_id}} - {{instance}}"
    }
   ]
  },
  {
   "title": "Produce request rate",
   "type": "graph",
   "description": "The average number of requests sent per second to the broker.\n",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(kafka_producer_producer_metrics_response_total{job=\"producer\"}[1m])",
     "legendFormat": "{{client_id}} - {{instance}}"
    }
   ]
  },
  {
   "title": "Request queue average time",
   "type": "graph",
   "description": "The average time in ms record batches spent in the send buffer.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 54 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_producer_producer_metrics_record_queue_time_avg{job=\"producer\"}",
     "legendFormat": "{{client_id}} - {{instance}}"
    }
   ]
  },
  {
   "title": "Record size average",
   "type": "graph",
   "description": "The average record size",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 54 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_producer_producer_metrics_record_size_avg{job=\"producer\"}",
     "legendFormat": "{{client_id}} - {{instance}}"
    }
   ]
  },
  {
   "title": "Request in flight",
   "type": "graph",
   "description": "The current number of in-flight requests awaiting a response.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 63 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_producer_producer_metrics_requests_in_flight{job=\"producer\"}",
     "legendFormat": "{{client_id}} - {{instance}}"
    }
   ]
  },
  {
   "title": "Metadata max age",
   "type": "graph",
   "description": "The age in seconds of the current producer metadata being used.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 63 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_producer_producer_metrics_metadata_age{job=\"producer\"}",
     "legendFormat": "{{client_id}} - {{instance}}"
    }
   ]
  },
  {
   "title": "Produce request throttle average",
   "type": "graph",
   "description": "The average time in ms a request was throttled by a broker",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 72 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_producer_producer_metrics_produce_throttle_time_avg{job=\"producer\"}",
     "legendFormat": "{{client_id}} - {{instance}}"
    }
   ]
  },
  {
   "title": "Buffer size available",
   "type": "graph",
   "description": "The total amount of buffer memory that is not being used (either unallocated or in the free list).",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 72 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_producer_producer_metrics_buffer_available_bytes{job=\"producer\"}",
     "legendFormat": "{{client_id}} - {{instance}}"
    }
   ]
  }
 ]
}