{
 "title": "Kafka Streams",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "env", "label": "Environment", "query": "label_values(env)" },
   {
    "name": "streams_app",
    "label": "Streams Application",
    "query": "label_values(kafka_streams_app_info, application_id)"
   },
   {
    "name": "thread_id",
    "query": "label_values(kafka_streams_stream_thread_metrics_process_total, thread_id)"
   }
  ]
 },
 "panels": [
  { "title": "Healthcheck", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Thread Numbers",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kafka_streams_app_info{alive_stream_threads!=\"\", job=\"streams\",env=\"$env\",client_id=~\"$streams_app(.*)\"}"
    }
   ]
  },
  {
   "title": "Active Task Numbers",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_streams_stream_thread_metrics_task_created_total{job=\"streams\",env=\"$env\",thread_id=~\"$streams_app(.*)\"})"
    }
   ]
  },
  {
   "title": "Close Task Numbers",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_streams_stream_thread_metrics_task_closed_total{job=\"streams\",env=\"$env\",thread_id=~\"$streams_app(.*)\"})"
    }
   ]
  },
  {
   "title": "Process Records Average",
   "type": "stat",
   "description": "The average number of records processed within an iteration.",
   "gridPos": { "h": 4, "w": 5, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kafka_streams_stream_thread_metrics_process_records_avg{env=\"$env\",thread_id=~\"$streams_app(.*)\"})"
    }
   ]
  },
  {
   "title": "Poll Records Average",
   "type": "stat",
   "description": "The average number of records processed within an iteration.",
   "gridPos": { "h": 4, "w": 5, "x": 17, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kafka_streams_stream_thread_metrics_poll_records_avg{env=\"$env\",thread_id=~\"$streams_app(.*)\"})"
    }
   ]
  },
  { "title": "Stream Threads", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Average Latency",
   "type": "graph",
   "description": "The average execution time in ms, for the respective operation, across all running tasks of this thread.",
   "gridPos": { "h": 5, "w": 13, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_streams_stream_thread_metrics_process_latency_avg{env=\"$env\", thread_id= \"$thread_id\"}",
     "legendFormat": "Process Latency AVG"
    },
    {
     "expr": "kafka_streams_stream_thread_metrics_commit_latency_avg{env=\"$env\", thread_id= \"$thread_id\"}",
     "legendFormat": "Commit Latency AVG"
    },
    {
     "expr": "kafka_streams_stream_thread_metrics_poll_latency_avg{env=\"$env\", thread_id= \"$thread_id\"}",
     "legendFormat": "Poll Latency AVG"
    },
    {
     "expr": "kafka_streams_stream_thread_metrics_punctuate_latency_avg{env=\"$env\", thread_id= \"$thread_id\"}",
     "legendFormat": "Punctuate Latency AVG"
    }
   ]
  },
  {
   "title": "Max Latency",
   "type": "graph",
   "description": "The max execution time in ms, for the respective operation, across all running tasks of this thread.",
   "gridPos": { "h": 5, "w": 11, "x": 13, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_streams_stream_thread_metrics_process_latency_max{env=\"$env\", thread_id= \"$thread_id\"}",
     "legendFormat": "Process Latency MAX"
    },
    {
     "expr": "kafka_streams_stream_thread_metrics_commit_latency_max{env=\"$env\", thread_id= \"$thread_id\"}",
     "legendFormat": "Commit Latency MAX"
    },
    {
     "expr": "kafka_streams_stream_thread_metrics_poll_latency_max{env=\"$env\", thread_id= \"$thread_id\"}",
     "legendFormat": "Poll Latency MAX"
    },
    {
     "expr": "kafka_streams_stream_thread_metrics_punctuate_latency_max{env=\"$env\", thread_id= \"$thread_id\"}",
     "legendFormat": "Punctuate Latency MAX"
    }
   ]
  },
  {
   "title": "Average Rate",
   "type": "graph",
   "description": "The average number of respective operations per second across all tasks.",
   "gridPos": { "h": 5, "w": 13, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_streams_stream_thread_metrics_process_rate{env=\"$env\", thread_id= \"$thread_id\"}",
     "legendFormat": "Process Rate"
    },
    {
     "expr": "kafka_streams_stream_thread_metrics_commit_rate{env=\"$env\", thread_id= \"$thread_id\"}",
     "legendFormat": "Commit Rate"
    },
    {
     "expr": "kafka_streams_stream_thread_metrics_poll_rate{env=\"$env\", thread_id= \"$thread_id\"}",
     "legendFormat": "Poll Rate"
    },
    {
     "expr": "kafka_streams_stream_thread_metrics_punctuate_rate{env=\"$env\", thread_id= \"$thread_id\"}",
     "legendFormat": "Punctuate Rate"
    }
   ]
  },
  {
   "title": "Poll & Process Average Records",
   "type": "graph",
   "description": "The average number of records processed & polled from consumer within an iteration",
   "gridPos": { "h": 5, "w": 11, "x": 13, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_streams_stream_thread_metrics_poll_records_avg{env=\"$env\", thread_id= \"$thread_id\"}",
     "legendFormat": "Poll records AVG"
    },
    {
     "expr": "kafka_streams_stream_thread_metrics_process_records_avg{env=\"$env\", thread_id= \"$thread_id\"}",
     "legendFormat": "Process records AVG"
    }
   ]
  },
  {
   "title": "Ratio",
   "type": "graph",
   "description": "The fraction of time the thread spent on the respective operations for active tasks.",
   "gridPos": { "h": 5, "w": 13, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_streams_stream_thread_metrics_process_ratio{env=\"$env\", thread_id= \"$thread_id\"}",
     "legendFormat": "Process Rate"
    },
    {
     "expr": "kafka_streams_stream_thread_metrics_commit_ratio{env=\"$env\", thread_id= \"$thread_id\"}",
     "legendFormat": "Commit Rate"
    },
    {
     "expr": "kafka_streams_stream_thread_metrics_poll_ratio{env=\"$env\", thread_id= \"$thread_id\"}",
     "legendFormat": "Poll Rate"
    },
    {
     "expr": "kafka_streams_stream_thread_metrics_punctuate_ratio{env=\"$env\", thread_id= \"$thread_id\"}",
     "legendFormat": "Punctuate Rate"
    }
   ]
  },
  { "title": "Stream Tasks", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Process Rate",
   "type": "graph",
   "description": "The average number of respective operations per second for this task.",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_streams_stream_task_metrics_process_rate{env=\"$env\", thread_id= \"$thread_id\"}",
     "legendFormat": "{{task_id}}"
    }
   ]
  },
  {
   "title": "Process Latency Rate",
   "type": "graph",
   "description": "The average  execution time in ns, for the respective operation for this task.",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_streams_stream_task_metrics_process_latency_avg{env=\"$env\", thread_id= \"$thread_id\"}",
     "legendFormat": "{{task_id}}"
    }
   ]
  },
  {
   "title": "Active Buffer Count Rate",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(kafka_streams_stream_task_metrics_active_buffer_count{env=\"$env\", thread_id= \"$thread_id\"}[5m])",
     "legendFormat": "{{task_id}}"
    }
   ]
  },
  { "title": "RocksDB Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Bytes Written Rate",
   "type": "graph",
   "description": "The average number of bytes written per second to the RocksDB state store.",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_streams_stream_state_metrics_bytes_written_rate{env=\"$env\", job=\"streams\", thread_id=\"$thread_id\"}",
     "legendFormat": "{{rocksdb_state_id}}-{{task_id}}"
    }
   ]
  },
  {
   "title": "Bytes Read Rate",
   "type": "graph",
   "description": "The average number of bytes read per second from the RocksDB state store.",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_streams_stream_state_metrics_bytes_read_rate{env=\"$env\", job=\"streams\", thread_id=\"$thread_id\"}",
     "legendFormat": "{{rocksdb_state_id}}-{{task_id}}"
    }
   ]
  },
  {
   "title": "Memtable Flushed Rate",
   "type": "graph",
   "description": "The average number of bytes flushed per second from the memtable to disk.",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_streams_stream_state_metrics_memtable_bytes_flushed_rate{env=\"$env\", job=\"streams\", thread_id=\"$thread_id\"}",
     "legendFormat": "{{rocksdb_state_id}}-{{task_id}}"
    }
   ]
  }
 ]
}